---
- name: Copy and Unzip installer
  unarchive:
    dest: "{{download_dir}}"
    src: "{{package_dir}}/oracle-xe-11.2.0-1.0.x86_64.rpm.zip"
    creates: "{{download_dir}}/Disk1"
    copy: yes

- name: Enable swap
  script: swap.sh
  args:
    creates: /swapfile

- name: Install required packages
  yum:
    name:
      - unzip
      - glibc
      - make
      - binutils
      - gcc
      - libaio
      - bc
      - python3
      - libnsl
    state: present
    disable_gpg_check: yes

- name: install oracle XE rpm
  yum:
    name: "{{download_dir}}/Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm"
    state: present
    disable_gpg_check: yes

- name: Install required python modules
  pip:
    name: cx_Oracle
    executable: /usr/bin/pip3

- name: Copy response template
  template:
    src: response.txt
    dest: "{{download_dir}}"

- name: Configure ddbb
  shell: "/etc/init.d/oracle-xe configure < {{download_dir}}/response.txt"
  register: command_result
  failed_when: "'is already configured' not in command_result.stdout and command_result.rc != 0"

- name: Copy env vbles script for autoload after boot
  copy:
    src: /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh
    dest: /etc/profile.d
    remote_src: yes
    owner: root
    group: root
    mode: 0644

- name: Force service start
  service:
    name: "{{oraclexe_service_name}}"
    state: started
